#pragma once
#include <iostream>
#include <thread>
#include "include/neuralNetwork.h"
#include "include/mnistData.h"
#include "include/readMnist.h"
#include <windows.h>
//#include <cuda.h>
#include <nlohmann/json.hpp>